"""Type stubs for libvirt-python."""

from typing import Any, List, Optional, Tuple, Union

class libvirtError(Exception):
    """Base libvirt exception."""
    pass

class virConnect:
    """libvirt connection object."""
    def defineXML(self, xml: str) -> Optional['virDomain']: ...
    def lookupByName(self, name: str) -> 'virDomain': ...
    def listAllDomains(self, flags: int = 0) -> List['virDomain']: ...
    def close(self) -> int: ...
    def getVersion(self) -> int: ...
    def getType(self) -> str: ...

class virDomain:
    """libvirt domain object."""
    def create(self) -> int: ...
    def destroy(self) -> int: ...
    def shutdown(self) -> int: ...
    def undefine(self) -> int: ...
    def state(self) -> Tuple[int, int]: ...
    def name(self) -> str: ...
    def UUIDString(self) -> str: ...
    def XMLDesc(self, flags: int = 0) -> str: ...
    def isActive(self) -> int: ...

def open(uri: Optional[str] = None) -> Optional[virConnect]: ...
def getVersion() -> int: ...

# Domain state constants
VIR_DOMAIN_NOSTATE: int
VIR_DOMAIN_RUNNING: int
VIR_DOMAIN_BLOCKED: int
VIR_DOMAIN_PAUSED: int
VIR_DOMAIN_SHUTDOWN: int
VIR_DOMAIN_SHUTOFF: int
VIR_DOMAIN_CRASHED: int
VIR_DOMAIN_PMSUSPENDED: int

# Domain flags
VIR_DOMAIN_UNDEFINE_MANAGED_SAVE: int
VIR_DOMAIN_UNDEFINE_SNAPSHOTS_METADATA: int
VIR_DOMAIN_UNDEFINE_NVRAM: int
VIR_DOMAIN_UNDEFINE_KEEP_NVRAM: int
