apiVersion: v1
kind: Service
metadata:
  name: slurm-compute
  namespace: slurm
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: slurm-compute
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurm-compute
  namespace: slurm
spec:
  serviceName: slurm-compute
  replicas: 3  # Number of compute nodes
  selector:
    matchLabels:
      app: slurm-compute
  template:
    metadata:
      labels:
        app: slurm-compute
    spec:
      containers:
      - name: slurmd
        image: slurm-base:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SLURM_ROLE
          value: "compute"
        - name: SLURM_PACKAGE_DIR
          value: "/tmp/slurm-packages"
        - name: SLURM_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: munge-key
          mountPath: /etc/munge/munge.key
          subPath: munge.key
          readOnly: true
        - name: slurm-packages
          mountPath: /tmp/slurm-packages
          readOnly: true
        - name: slurm-config
          mountPath: /etc/slurm
        - name: slurm-logs
          mountPath: /var/log/slurm
        - name: slurm-spool
          mountPath: /var/spool/slurmd
        ports:
        - containerPort: 6818
          name: slurmd
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: munge-key
        secret:
          secretName: slurm-munge-key
      - name: slurm-packages
        hostPath:
          path: /path/to/build/packages/slurm  # Update this path
          type: Directory
      - name: slurm-config
        configMap:
          name: slurm-config
      - name: slurm-logs
        emptyDir: {}
      - name: slurm-spool
        emptyDir: {}

