apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-db-pvc
  namespace: slurm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-state-pvc
  namespace: slurm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

