apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-storage
  namespace: mlops
  labels:
    app: postgresql
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
