#!/usr/bin/env python3
"""
Generate Ansible inventory from cluster.yaml configuration

This is a temporary workaround until ai-how implements inventory generation.

The inventory uses the same SSH keys and username as the Packer build system:
- Username: admin (defined in packer/common/cloud-init/*.yml)
- SSH Key: build/shared/ssh-keys/id_rsa (generated by Packer build)
"""

import sys
import yaml
import os
import json
from pathlib import Path


def generate_inventory(config_path: str, cluster_name: str, ssh_key_path: str = None, ssh_username: str = "admin") -> str:
    """Generate Ansible inventory from cluster configuration.

    Args:
        config_path: Path to cluster configuration YAML file
        cluster_name: Name of cluster to generate inventory for
        ssh_key_path: Path to SSH private key (default: build/shared/ssh-keys/id_rsa)
        ssh_username: SSH username (default: admin, matching Packer build)
    """

    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)

    if 'clusters' not in config:
        raise ValueError("No clusters found in configuration")

    if cluster_name not in config['clusters']:
        raise ValueError(f"Cluster '{cluster_name}' not found in configuration")

    cluster = config['clusters'][cluster_name]
    inventory_lines = []

    # Default SSH key path from Packer build system
    if ssh_key_path is None:
        # Resolve relative to project root
        project_root = Path(__file__).parent.parent
        ssh_key_path = project_root / "build" / "shared" / "ssh-keys" / "id_rsa"
        ssh_key_path = str(ssh_key_path.absolute())

    # Verify SSH key exists
    if not Path(ssh_key_path).exists():
        print(f"⚠️  WARNING: SSH private key not found at: {ssh_key_path}", file=sys.stderr)
        print(f"   Run 'make config' or build Packer images to generate SSH keys", file=sys.stderr)

    # SSH connection arguments
    ssh_args = f"ansible_ssh_private_key_file={ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

    # Generate HPC controller inventory
    if 'controller' in cluster:
        inventory_lines.append("[hpc_controllers]")
        controller = cluster['controller']
        ip = controller.get('ip_address', '192.168.100.10')
        hostname = f"{cluster_name}-controller"
        slurm_name = "controller"
        inventory_lines.append(f"{hostname} ansible_host={ip} slurm_node_name={slurm_name} ansible_user={ssh_username} {ssh_args}")
        inventory_lines.append("")

    # Generate compute nodes inventory
    # Separate GPU nodes from regular compute nodes based on pcie_passthrough configuration
    if 'compute_nodes' in cluster:
        regular_compute_nodes = []
        gpu_compute_nodes = []

        for idx, node in enumerate(cluster['compute_nodes'], start=1):
            # Check if node has GPU configuration
            has_gpu = False
            if 'pcie_passthrough' in node and node['pcie_passthrough'].get('enabled', False):
                devices = node['pcie_passthrough'].get('devices', [])
                has_gpu = any(d.get('device_type') == 'gpu' for d in devices)

            ip = node.get('ip', f'192.168.100.{10+idx}')
            hostname = f"{cluster_name}-compute{idx:02d}"
            slurm_name = f"compute-{idx:02d}"
            node_line = f"{hostname} ansible_host={ip} slurm_node_name={slurm_name} ansible_user={ssh_username} {ssh_args}"

            if has_gpu:
                gpu_compute_nodes.append(node_line)
            else:
                regular_compute_nodes.append(node_line)

        # Generate hpc_compute_nodes group (regular CPU nodes)
        if regular_compute_nodes:
            inventory_lines.append("[hpc_compute_nodes]")
            inventory_lines.extend(regular_compute_nodes)
            inventory_lines.append("")

        # Generate hpc_gpu_nodes group (GPU-enabled nodes)
        if gpu_compute_nodes:
            inventory_lines.append("[hpc_gpu_nodes]")
            inventory_lines.extend(gpu_compute_nodes)
            inventory_lines.append("")

    # Generate group variables
    inventory_lines.append("[hpc:children]")
    inventory_lines.append("hpc_controllers")
    if 'compute_nodes' in cluster:
        # Only include groups that have hosts
        if regular_compute_nodes:
            inventory_lines.append("hpc_compute_nodes")
        if gpu_compute_nodes:
            inventory_lines.append("hpc_gpu_nodes")
    inventory_lines.append("")

    inventory_lines.append("[hpc:vars]")
    inventory_lines.append("ansible_python_interpreter=/usr/bin/python3")

    # Extract VirtIO-FS mount configuration from controller
    if 'controller' in cluster and 'virtio_fs_mounts' in cluster['controller']:
        virtio_fs_mounts = cluster['controller']['virtio_fs_mounts']
        if virtio_fs_mounts:  # Only add if not empty
            # Convert to JSON string for Ansible variable (properly escaped)
            virtio_fs_json = json.dumps(virtio_fs_mounts, separators=(',', ':'))
            inventory_lines.append(f"virtio_fs_mounts={virtio_fs_json}")
            print(f"✅ Found {len(virtio_fs_mounts)} VirtIO-FS mount(s) in controller configuration", file=sys.stderr)
        else:
            print("ℹ️  VirtIO-FS mounts defined but empty in controller configuration", file=sys.stderr)
    else:
        print("ℹ️  No VirtIO-FS mounts found in controller configuration", file=sys.stderr)

    # Extract BeeGFS configuration from storage section
    if 'storage' in cluster and 'beegfs' in cluster['storage']:
        beegfs_config = cluster['storage']['beegfs']
        if beegfs_config.get('enabled', False):
            # Convert to JSON string for Ansible variable
            beegfs_json = json.dumps(beegfs_config, separators=(',', ':'))
            inventory_lines.append(f"beegfs_config={beegfs_json}")
            inventory_lines.append(f"beegfs_enabled=true")
            print(f"✅ BeeGFS enabled with mount point: {beegfs_config.get('mount_point', '/mnt/beegfs')}",
                  file=sys.stderr)
        else:
            inventory_lines.append(f"beegfs_enabled=false")
            print("ℹ️  BeeGFS disabled in cluster configuration", file=sys.stderr)
    else:
        inventory_lines.append(f"beegfs_enabled=false")
        print("ℹ️  No BeeGFS configuration found in cluster", file=sys.stderr)

    inventory_lines.append("")

    return "\n".join(inventory_lines)


def main():
    if len(sys.argv) < 3:
        print("Usage: generate-ansible-inventory.py <config_file> <cluster_name> [output_file] [ssh_key_path] [ssh_username]", file=sys.stderr)
        print("", file=sys.stderr)
        print("Arguments:", file=sys.stderr)
        print("  config_file    - Path to cluster configuration YAML", file=sys.stderr)
        print("  cluster_name   - Name of cluster to generate inventory for", file=sys.stderr)
        print("  output_file    - (Optional) Path to write inventory (default: stdout)", file=sys.stderr)
        print("  ssh_key_path   - (Optional) Path to SSH private key (default: build/shared/ssh-keys/id_rsa)", file=sys.stderr)
        print("  ssh_username   - (Optional) SSH username (default: admin)", file=sys.stderr)
        print("", file=sys.stderr)
        print("Note: Username 'admin' and SSH keys from 'build/shared/ssh-keys/' match Packer build configuration", file=sys.stderr)
        sys.exit(1)

    config_path = sys.argv[1]
    cluster_name = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) > 3 else None
    ssh_key_path = sys.argv[4] if len(sys.argv) > 4 else None
    ssh_username = sys.argv[5] if len(sys.argv) > 5 else "admin"

    try:
        inventory = generate_inventory(config_path, cluster_name, ssh_key_path, ssh_username)

        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                f.write(inventory)
            print(f"✅ Inventory written to: {output_path}")
            if ssh_key_path:
                print(f"   Using SSH key: {ssh_key_path}")
            else:
                print(f"   Using SSH key: build/shared/ssh-keys/id_rsa (from Packer build)")
            print(f"   Using SSH username: {ssh_username}")
        else:
            print(inventory)

    except Exception as e:
        print(f"❌ Error generating inventory: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
